package:
  name: molminer
  version: "1.0.0"

source:
    path: .

build:
    number: 0
    script_env:
        - MM_DEP
    entry_points:
        - molminer = molminer.cli:cli

requirements:
    build:
    - python 3.5*
    - setuptools
    run:
    - python 3.5*
    - rdkit
    - click
    - joblib
    - python-magic
    - molvs
    - pubchempy
    - chemspipy

test:
    imports:
        - molminer
        - molminer.OSRA
        - molminer.ChemSpot
        - molminer.OPSIN
        - molminer.Extractor
    commands:
        - molminer --version
        - molminer --help

about:
  home: https://github.com/gorgitko/molminer
  license: MIT
  summary: A command-line tool and library for extraction of chemical entities from text and 2D structures.