package:
  name: molminer
  version: "1.0.0"

source:
    path: .  # [linux]

build:
  number: 0
  script_env:
    - MM_DEP
  entry_points:
    - molminer = molminer.cli:cli

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - rdkit >=2016.09.4*
    - click
    - joblib >=0.11*
    - python-magic
    - molvs >=0.0.9*

test:
  imports:
    - molminer
  commands:
    - molminer --version
    - molminer --help

about:
  #home:
  license: MIT